github:
  username: ${{ secrets.GITHUB_USERNAME }}
  token:    ${{ secrets.PAT }}

codeowners:
- path:  "*"
  owner: "@initializ-buildpacks/utilities-maintainers"

package:
  repositories:   ["docker.io/initializbuildpacks/image-labels"]
  register:       true
  registry_token: ${{ secrets.PAT }}

docker_credentials:
- registry: docker.io
  username: ${{ secrets.INITIALIZ_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.INITIALIZ_BUILDPACKS_DOCKERHUB_PASSWORD }}
